# @summary List of loki components
type Loki::Target = Array[Enum[
    'all',
    'analytics',
    'backend',
    'bloom-builder',
    'bloom-compactor',
    'bloom-gateway',
    'bloom-planner',
    'bloom-store',
    'cache-generation-loader',
    'compactor',
    'distributor',
    'index-gateway',
    'ingester',
    'ingester-querier',
    'overrides-exporter',
    'pattern-ingester',
    'querier',
    'query-frontend',
    'query-scheduler',
    'ruler',
    'read',
    'table-manager',
    'write' # lint:ignore:trailing_comma
]]
